#!/usr/bin/env python3
"""
Round 5, variance: more ways to say the same thing, so a stretch of the
same weather doesn't show the same words.

    python3 review/rounds/make_round5.py

- Fact lines: new wordings for every situation, five in all for the
  common ones. Shown on the page rendered (time words filled in); the
  template behind each is kept in the round file for build_pools.py.
- Flavour lines: one reworded version of every line the owner kept or
  starred. Same joke, different words; German variants also drop the
  Austrian markers the owner flagged ("eh", "heuer", "Wennst").

Written by hand, not by a writer agent: this is editing, not invention.
"""

import hashlib
import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
ROUND = "2026-10-variants"

FACTS = {
    "en": {
        "steady": ["You're dressed right for the whole day.",
                   "That outfit will see you through the whole day.",
                   "Nothing to change today. What you have on is right.",
                   "What you have on works from now until tonight."],
        "steady_evening": ["You're dressed right for the rest of the evening.",
                           "That outfit will see you through the evening.",
                           "Nothing to change tonight. What you have on is right.",
                           "The rest of the evening needs nothing more than this."],
        "steady_hot": ["It's hot all day. Bring water and stay in the shade.",
                       "The heat stays all day, so keep water with you.",
                       "No break from the heat today. Water and shade help.",
                       "It stays hot until tonight, so drink plenty and find shade."],
        "steady_cold": ["It's cold all day. Keep everything on.",
                        "The cold stays all day, so everything stays on.",
                        "No warming up today. Keep it all on.",
                        "It stays this cold until tonight, so don't take anything off."],
        "w_scarf": ["You can take off the hat, scarf and gloves {WHEN}.",
                    "{WHEN} it's mild enough to lose the hat, scarf and gloves."],
        "w_coat": ["You can take the winter coat off {WHEN}.",
                   "{WHEN} it's warm enough to lose the winter coat.",
                   "It warms up {WHEN}, so the winter coat can come off."],
        "w_jacket": ["The jacket can come off {WHEN}.",
                     "{WHEN} it's warm enough to lose the jacket.",
                     "It warms up {WHEN}, so the jacket can come off."],
        "w_hoodie": ["The sweater can come off {WHEN}.",
                     "{WHEN} it's warm enough to lose the sweater.",
                     "It warms up {WHEN}, so the sweater can come off."],
        "w_water": ["{WHEN} it gets hot. Bring water.",
                    "It heats up {WHEN}, so take water with you."],
        "c_scarf": ["{WHEN} it gets cold enough for a hat, scarf and gloves.",
                    "Bring a hat, scarf and gloves. It gets colder {WHEN}."],
        "c_coat": ["{WHEN} it gets cold enough for the winter coat.",
                   "Bring the winter coat. It gets colder {WHEN}."],
        "c_jacket": ["{WHEN} it gets cool enough for a jacket.",
                     "Bring a jacket. It cools down {WHEN}.",
                     "It gets cooler {WHEN}, so take a jacket along."],
        "c_hoodie": ["{WHEN} it gets cool enough for a sweater.",
                     "Bring a sweater. It cools down {WHEN}.",
                     "It gets cooler {WHEN}, so take a sweater along."],
        "c_relief": ["The heat eases {WHEN}, but it stays warm.",
                     "{WHEN} it gets a little less hot. Still warm, though.",
                     "It cools down a bit {WHEN}. Warm all the same.",
                     "Some relief from the heat {WHEN}, but it stays warm."],
        "arc_warmer": ["{G} can come off {WHEN} and stay off.",
                       "You can take {G} off {WHEN}. You won't need {GP} again today.",
                       "{WHEN} {G} can come off for the rest of the day."],
        "arc_level": ["You can take {G} off {WHEN}. You'll want {GP} back {WHEN2}.",
                      "Take {G} off {WHEN}, put {GP} back on {WHEN2}.",
                      "{G} can come off {WHEN}. Keep {GP} handy for {WHEN2}."],
        "arc_colder": ["You can take {G} off {WHEN}. {WHEN2} you'll want {GP} back, and a layer more."],
        "shorts_early": ["A cool start, then shorts weather {WHEN}.",
                         "It's cool now, but {WHEN} it's warm enough for shorts."],
        "p_wetter": ["A shower comes through {WHENP}, so take the umbrella.",
                     "Bring the umbrella. There's a shower {WHENP}.",
                     "Expect a shower {WHENP}. The umbrella's worth taking.",
                     "{WHENP} there's a shower, so the umbrella comes along."],
        "p_wetter_long": ["The rain starts {WHENP} and doesn't stop. Bring the umbrella.",
                          "Bring the umbrella. Once it starts raining {WHENP}, it keeps going.",
                          "{WHENP} the rain sets in for good. Bring the umbrella."],
        "p_wetter_maybe": ["There's a chance of rain {WHENP}. An umbrella wouldn't hurt.",
                           "Rain is possible {WHENP}, so maybe take the umbrella.",
                           "It could rain {WHENP}. Take the umbrella to be safe."],
        "p_stays_wet": ["It's raining all day. Bring the umbrella.",
                        "The rain doesn't stop today, so take the umbrella.",
                        "Rain all day long. The umbrella comes along."],
        "p_drier": ["It stops raining later. Until then, the umbrella.",
                    "Take the umbrella for now. The rain stops later.",
                    "The rain eases off later, but bring the umbrella for now."],
        "p_wet_again": ["The rain takes a break, then comes back {WHENP}. Keep the umbrella.",
                        "A dry spell, then more rain {WHENP}. Keep the umbrella with you."],
        "p_snow_coming": ["Snow starts {WHENP}.", "Expect snow {WHENP}.", "{WHENP} it starts to snow."],
        "p_stays_wet_snow": ["It's snowing all day.", "The snow keeps coming all day."],
        "p_drier_snow": ["It stops snowing later.", "The snow eases off later."],
        "p_wet_again_snow": ["The snow takes a break, then comes back {WHENP}.",
                             "A break in the snow, then more {WHENP}."],
    },
    "de": {
        "steady": ["Du bist für den ganzen Tag richtig angezogen.",
                   "Mit dem, was du anhast, kommst du gut durch den Tag.",
                   "Heute musst du nichts ändern. Was du anhast, passt.",
                   "Was du anhast, passt bis zum Abend."],
        "steady_evening": ["Du bist für den Abend richtig angezogen.",
                           "Mit dem, was du anhast, kommst du gut durch den Abend.",
                           "Heute Abend musst du nichts mehr ändern.",
                           "Was du anhast, reicht für den ganzen Abend."],
        "steady_hot": ["Heiß bis zum Abend. Nimm Wasser mit und bleib im Schatten.",
                       "Die Hitze bleibt den ganzen Tag, also viel trinken.",
                       "Heute kühlt's nicht ab. Wasser mitnehmen, Schatten suchen.",
                       "Es bleibt heiß bis zum Abend, also immer Wasser dabeihaben."],
        "steady_cold": ["Kalt bis zum Abend, da bleibt alles an.",
                        "Die Kälte bleibt den ganzen Tag, also nichts ausziehen.",
                        "Heute wird's nicht wärmer. Lass alles an.",
                        "Es bleibt so kalt bis zum Abend, da kommt nichts runter."],
        "w_scarf": ["{WHEN} kannst du Mütze, Schal und Handschuhe ablegen.",
                    "{WHEN} wird's mild genug, dann können Mütze, Schal und Handschuhe weg."],
        "w_coat": ["{WHEN} kannst du die Winterjacke ausziehen.",
                   "{WHEN} ist es warm genug, dann brauchst du keine Winterjacke mehr.",
                   "{WHEN} wird's wärmer, dann kann die Winterjacke weg."],
        "w_jacket": ["{WHEN} kannst du die Jacke ausziehen.",
                     "{WHEN} ist es warm genug, dann brauchst du keine Jacke mehr.",
                     "{WHEN} wird's wärmer, dann kann die Jacke weg."],
        "w_hoodie": ["{WHEN} kannst du den Pulli ausziehen.",
                     "{WHEN} ist es warm genug, dann brauchst du keinen Pulli mehr.",
                     "{WHEN} wird's wärmer, dann kann der Pulli weg."],
        "w_water": ["{WHEN} wird's heiß, also Wasser einpacken.",
                    "{WHEN} kommt die Hitze, nimm genug zu trinken mit."],
        "c_scarf": ["{WHEN} wird's kalt genug für Mütze, Schal und Handschuhe.",
                    "Pack Mütze, Schal und Handschuhe ein, {WHEN} wird's kälter."],
        "c_coat": ["{WHEN} wird's kalt genug für die Winterjacke.",
                   "Nimm die Winterjacke mit, {WHEN} wird's kälter."],
        "c_jacket": ["{WHEN} wird's frisch genug für eine Jacke.",
                     "Nimm eine Jacke mit, {WHEN} kühlt's ab.",
                     "Pack eine Jacke ein, {WHEN} wird's kühler."],
        "c_hoodie": ["{WHEN} wird's frisch genug für einen Pulli.",
                     "Nimm einen Pulli mit, {WHEN} kühlt's ab.",
                     "Pack einen Pulli ein, {WHEN} wird's kühler."],
        "c_relief": ["{WHEN} wird's etwas weniger heiß, aber warm bleibt's.",
                     "{WHEN} kühlt's ein bisschen ab, warm ist's trotzdem.",
                     "Die Hitze lässt {WHEN} nach, warm bleibt's aber.",
                     "{WHEN} wird's angenehmer, aber immer noch warm."],
        "arc_warmer": ["{WHEN} {GV} weg, und du brauchst {GP} heute nicht mehr.",
                       "{WHEN} {GV} weg. Heute brauchst du {GP} nicht mehr."],
        "arc_level": ["{WHEN} {GV} weg. {WHEN2} brauchst du {GP} aber wieder.",
                      "{WHEN} {GV} weg, aber behalt {GP} griffbereit für {WHEN2}."],
        "arc_colder": ["{WHEN} {GV} weg. {WHEN2} wird's kälter als jetzt, nimm eine Schicht mehr mit."],
        "shorts_early": ["Frischer Start, {WHEN} wird's warm genug für Shorts.",
                         "Jetzt noch kühl, {WHEN} ist es Shorts-Wetter."],
        "p_wetter": ["{WHENP} gibt's einen Schauer, der Schirm sollte mit.",
                     "Nimm den Schirm mit, {WHENP} kommt ein Schauer.",
                     "{WHENP} zieht ein Schauer durch, also Schirm einpacken.",
                     "Schirm nicht vergessen, {WHENP} gibt's einen Schauer."],
        "p_wetter_long": ["{WHENP} setzt Regen ein und bleibt. Nimm den Schirm mit.",
                          "Nimm den Schirm mit, {WHENP} fängt's an zu regnen, und zwar länger.",
                          "{WHENP} beginnt der Regen, und der bleibt. Schirm einpacken."],
        "p_wetter_maybe": ["{WHENP} ist Regen möglich, nimm vielleicht den Schirm mit.",
                           "{WHENP} kann's regnen. Mit Schirm bist du auf der sicheren Seite.",
                           "Vielleicht regnet's {WHENP}. Der Schirm schadet nicht."],
        "p_stays_wet": ["Regen bis zum Abend, der Schirm muss mit.",
                        "Heute hört's nicht auf zu regnen, also Schirm mitnehmen.",
                        "Den ganzen Tag Regen. Ohne Schirm geht's nicht."],
        "p_drier": ["Später hört's auf zu regnen. Bis dahin Schirm.",
                    "Nimm den Schirm mit, der Regen hört erst später auf.",
                    "Der Regen lässt später nach, für jetzt brauchst du den Schirm."],
        "p_wet_again": ["Erst eine Regenpause, {WHENP} regnet's wieder. Der Schirm bleibt dabei.",
                        "Zwischendurch trocken, {WHENP} kommt der Regen zurück. Schirm mitnehmen."],
        "p_snow_coming": ["{WHENP} fängt's an zu schneien.", "{WHENP} kommt Schnee.",
                          "Mach dich auf Schnee gefasst, {WHENP} geht's los."],
        "p_stays_wet_snow": ["Schnee bis zum Abend.", "Heute hört's nicht auf zu schneien."],
        "p_drier_snow": ["Später hört's auf zu schneien.", "Der Schneefall lässt später nach."],
        "p_wet_again_snow": ["Erst eine Schneepause, {WHENP} schneit's wieder.",
                             "Zwischendurch Ruhe, {WHENP} schneit's wieder."],
    },
}

# Original line -> its reworded variant. Same joke, new words.
FLAVOUR = {
    "en": {
        "I'm a screen on a wall. Even I'd go outside today.": "Even a screen bolted to a wall wants to go out today.",
        "Days like this, I get a two-second glance. Rude, but fair.": "On days like this you barely look at me. Fair enough.",
        "Easy day to forecast. I'll still take the credit.": "Not my hardest forecast. I'm taking the credit anyway.",
        "Lovely out. I'll be here, refreshing.": "Lovely out there. I'll stay in here, refreshing.",
        "Today the weather looks almost as good as I do.": "The weather's nearly as easy on the eyes as I am today.",
        "I've had firmware updates more exciting than today.": "Today has the thrill of a firmware update. A small one.",
        "It takes real talent to make today look interesting.": "Making today look interesting takes skill. Lucky you've got me.",
        "Other screens get to show paintings. I get today's weather.": "Somewhere a screen is showing a Monet. I got today.",
        "Thrilling stuff. I'm on the edge of my wall.": "Gripping weather. I can barely stay on the wall.",
        "I was grey before winter made it cool.": "Grey was my look long before winter tried it.",
        "I'm staying on the wall where it's warm.": "I'll be on the wall. The warm side.",
        "My only weakness is the cold. Kidding, I don't have one.": "The cold can't touch me. Nothing can. I'm on a wall.",
        "Today's drawing is mostly coat. I'm very proud of the coat.": "Today I'm showing mostly coat. Proud of that coat.",
        "Thin, pale and cool. I was made for this.": "Flat, pale and cool. Built for days like this.",
        "I'll be here in the shade of your hallway.": "I'll sit this one out in your nice shady hallway.",
        "No fan, no sweat. Perks of being a screen.": "No sweat here. One of the perks of being a screen.",
        "Someone turned the outside up too far. Don't look at me.": "Somebody cranked the outside too high. Wasn't me.",
        "I don't get wet. Perks of living indoors.": "Staying dry is easy when you live on a wall.",
        "I'd make a terrible umbrella. Gorgeous, but terrible.": "As an umbrella I'd be useless. Beautiful, but useless.",
        "I'll be on the wall, dry and smug.": "Dry and smug, right here on the wall.",
        "I'm very good for umbrella sales.": "The umbrella industry owes me a thank-you note.",
        "No sad cloud icons here. I have taste.": "You won't get a sad little cloud icon from me. Standards.",
        "Nothing gets me looked at like a chance of rain.": "A chance of rain, and suddenly everyone checks on me.",
        "Rain makes everything shiny. I stay tastefully matte.": "Rain makes it all glossy out there. I prefer matte.",
        "Rain or not, my humour stays bone dry.": "Whatever the sky does, my humour stays dry.",
        "I've never seen snow. Describe it to me later.": "I've only heard about snow. Tell me everything later.",
        "In snow, I'd leave a perfect rectangle. Angels are for amateurs.": "My snow angel would be a perfect rectangle. Classy.",
        "Snow is rain with better presentation. I respect that.": "Snow is just rain that cares about presentation.",
        "I'm the only thing today that won't change its mind.": "Today everything changes its mind except me.",
        "Make up your mind, weather. Some of us refresh on a schedule.": "Pick one, weather. Some of us run on a schedule.",
        "The sky's going through something. I'm staying out of it.": "The sky's having a day. I'm keeping my distance.",
        "Today has a plot twist. I've read ahead.": "Today's got a twist in it. I already know the ending.",
        "By now the other screens are all glowing. Tacky.": "Every other screen is glowing by now. So tacky.",
        "Evenings are for unwinding, apparently. I've never been wound.": "Evenings are for unwinding, they say. I was never wound.",
        "Going out is overrated. Says a screen that's never been out.": "Going out is overrated, says the screen that never has.",
        "My plans for tonight: this wall. It's a great wall.": "Tonight's plan: same wall as always. Great wall, though.",
        "The weather's the easy part of tonight.": "Of everything tonight, the weather is the easy bit.",
        "I can hold this picture all night without power. Try that.": "I'll hold this picture all night on no power. Your move.",
        "I don't need beauty sleep. Clearly.": "Beauty sleep? Clearly I don't need any.",
        "No blue light from me. I'm the screen that lets you sleep.": "I'm the one screen that won't keep you up. You're welcome.",
        "Nothing new from me tonight. Sleep well.": "That's all from me tonight. Sleep well.",
        "Perfect weather. I can't leave the wall. What's your excuse?": "I'm stuck on a wall. What's keeping you in today?",
        "A good day for pretending you'll go for a run.": "Perfect weather to talk about going for a run.",
        "I'll pretend I didn't see you stay in.": "If you stay in, I'll act like I didn't notice.",
        "Try not to make your good mood everyone's problem.": "Go easy with the good mood. Others have to see it.",
        "You'll open a window and feel like you've achieved something.": "You'll open one window and call it a productive day.",
        "You'll take one short walk and talk about it all week.": "One short walk today, and we'll hear about it for days.",
        "Today's as predictable as your lunch order.": "Today's as surprising as your usual coffee order.",
        "Unremarkable out there. You'll fit right in.": "Nothing special out there. You'll blend right in.",
        "You'll call it 'fresh' to sound like an outdoors person.": "You'll call it 'crisp' like you go hiking or something.",
        "Your usual jacket, your usual route. Living on the edge.": "Same jacket, same route. You wild thing.",
        "Taking that layer off might be the highlight of your day.": "That layer coming off could be the peak of your day.",
        "Today you're your own coat rack. Congratulations.": "Today you're a coat rack with legs. Well done.",
        "You'll be a bit too warm before you admit I was right.": "You'll overheat a little before you admit I was right.",
        "Carrying a layer you don't need yet. How very grown-up.": "A layer you won't need for hours. Look at you, prepared.",
        "Leave it behind and you'll think of me later. Not fondly.": "Forget it and you'll think of me later. Not kindly.",
        "You'll put it on later and act like it was your idea.": "Later you'll put it on as if you thought of it.",
        "Gloves off to use your phone, every time. Brilliant system.": "Gloves off for every text. Truly a flawless system.",
        "I've drawn you a warm coat. The least you can do is wear it.": "That coat up there? Wear it. I worked hard on it.",
        "Reading me slowly won't make it any warmer.": "Staring at me longer won't warm it up.",
        "Shoulders up by your ears all day. Very elegant.": "Shoulders at ear height all day. So graceful.",
        "Twice your usual walking speed today. Still not exercise.": "You'll walk twice as fast today. Still not cardio.",
        "You'll make that noise once you're outside. You know the one.": "The second you step out, you'll make that sound. You know it.",
        "You'll say it's not that cold. Your face will disagree.": "'It's not that cold,' you'll say. Your ears won't agree.",
        "Your nose will turn a colour I can't even display.": "Your nose is about to go a colour I can't show.",
        "Anything flat becomes a fan today. Not me, please.": "Today you'll fan yourself with anything flat. Not me.",
        "I don't sweat. You will.": "One of us is about to sweat. Not me.",
        "You asked for warm weather. Careful what you wish for.": "Remember wishing for summer? This is what you get.",
        "You'll come home looking less crisp than this drawing.": "You'll come home a lot less crisp than you left.",
        "You'll search 'ice cream near me' later. Twice.": "'Ice cream near me' is in your future. Twice.",
        "You're about to have strong opinions about air conditioning.": "Get ready to have feelings about air conditioning.",
        "I refresh every few minutes. Wet socks don't.": "I refresh every few minutes. Your socks won't.",
        "If you come back soaked, don't drip near me.": "Come back soaked if you must. Just don't drip on me.",
        "Try to bring the umbrella home. Unlike the last three.": "This umbrella's coming home, right? Unlike the others.",
        "Umbrella chicken with strangers. You always flinch first.": "Another day of umbrella chicken. You'll blink first.",
        "Whatever the sky does, you'll say you knew. You didn't.": "Whatever happens, you'll claim you saw it coming. Sure.",
        "You'll still check your phone. As if it knows something I don't.": "You'll double-check on your phone. As if it knows better.",
        "'Proper snow,' you'll say. As if there's improper snow.": "You'll call it 'proper snow'. Name one improper kind.",
        "Give it an hour, then you'll take the snow personally.": "An hour from now, the snow will feel personal.",
        "Shake the snow off before you come near me.": "Snow stays at the door. Not near me.",
        "Try not to slip. I can't call anyone.": "Don't fall. I have no way of getting help.",
        "Whoever's nearby gets your snow commentary. Usually me.": "Someone's getting your full snow report. Usually me.",
        "Complaining it's warm, then that it isn't. You've got range.": "Too warm, then too cold. You'll complain about both.",
        "I give it even odds you lose that layer by tonight.": "Fifty-fifty that layer goes missing by tonight.",
        "I've changed this drawing in my head twice already.": "I've redressed you in my head twice already.",
        "The warm bit will make you insufferable.": "The warm part of today will go to your head.",
        "Today's weather has more mood swings than you. Barely.": "The weather's as moody as you today. Nearly.",
        "You'll feel very clever for about half the day.": "You'll feel smart until about lunchtime.",
        "Another evening of walking past me without a thank-you.": "Another evening, another walk past me. No thanks, as usual.",
        "Going out? Look better than this drawing.": "If you're going out, try to look better than this.",
        "I'll be here all night. Unlike your motivation.": "I'll still be here at midnight. Your motivation won't.",
        "Whatever your plans are, I'm not invited. Fine.": "Whatever you're doing tonight, I wasn't invited. Noted.",
        "You'll read all this, then do what you were going to anyway.": "You'll read this and then do exactly what you planned.",
        "Bed's right there and you're choosing me. I'm touched.": "There's a bed nearby and you picked me. Flattering.",
        "If you're heading out now, I admire the commitment.": "Going out at this hour? Respect.",
        "Still up? I'm a wall decoration and even I'm tired.": "Still awake? Even the decor is tired, and that's me.",
        "Tomorrow-you is already annoyed with tonight-you.": "Morning-you is going to have words with tonight-you.",
        "You've looked at me a lot today. Go to bed.": "You've checked me plenty today. Bed.",
    },
    "de": {
        "Bei dem Wetter kann man nicht mal gescheit schlecht drauf sein.": "Bei dem Wetter fällt selbst mir schlechte Laune schwer.",
        "Bei dem Wetter muss man raus, heißt's immer. Muss man gar nicht.": "„Bei dem Wetter muss man raus.“ Wer sagt das eigentlich?",
        "Nichts auszusetzen. Das ärgert mich fast.": "Ich find nichts zum Meckern. Das ärgert mich.",
        "Wetter wie im Reiseprospekt. Bloß halt hier.": "Wie im Urlaubskatalog. Nur halt vor der Haustür.",
        "Ein Wetter für Leute ohne Meinung.": "Wetter für Leute, die beim Essen „passt schon“ sagen.",
        "Nicht mal das Wetter taugt heut als Ausrede.": "Heute taugt nicht mal das Wetter als Ausrede.",
        "Mir kann's egal sein. Ich häng hier nackt an der Wand.": "Mich betrifft das nicht. Ich häng hier ohne alles an der Wand.",
        "Nachher sagt wieder jeder: Ganz schön frisch geworden.": "Gleich heißt's wieder überall: Ist aber frisch geworden.",
        "Bei der Kälte schmeckt sogar Glühwein.": "Bei der Kälte trinkt man sogar Glühwein freiwillig.",
        "Kalt ist's. Wie jedes Jahr, und jedes Jahr sind alle überrascht.": "Jedes Jahr wird's kalt. Und jedes Jahr tun alle überrascht.",
        "Saukalt. Mehr gibt's nicht zu sagen.": "Saukalt. Mehr fällt mir dazu nicht ein.",
        "Da hätt die Oma keinen aus dem Haus gelassen.": "Bei dem Wetter hätte Oma die Haustür abgesperrt.",
        "Gleich reißt einer zum Stoßlüften alle Fenster auf.": "Und gleich wird trotzdem wieder stoßgelüftet.",
        "Irgendein Depp läuft trotzdem in kurzen Hosen rum.": "Einer läuft trotzdem in Shorts rum. Einen gibt's immer.",
        "Kälte ist gesund, sagen immer die, die drinnen sitzen.": "„Kälte härtet ab“, sagen die mit der Heizung auf fünf.",
        "Und dann gibt's Leut', die sagen, sie mögen den Winter.": "Und dann gibt's Leute, die den Winter mögen. Angeblich.",
        "Im Baumarkt gibt's wieder keinen Ventilator mehr.": "Ventilatoren sind im Baumarkt heute wieder ausverkauft.",
        "Bei der Hitze stellen sich die Leute dann noch an den Grill.": "Bei der Hitze noch grillen. Muss man wollen.",
        "Gleich sagt wieder einer: Ist aber eine trockene Hitze.": "Gleich kommt wieder: „Aber es ist eine trockene Hitze.“",
        "Heut ist mir sogar das Meckern zu anstrengend.": "Zum Meckern ist es mir heute zu heiß. Fast.",
        "Hitzefrei gibt's nur für Schüler. Der Rest muss durch.": "Hitzefrei kriegen nur die Schüler. Alle anderen schwitzen.",
        "In der Bahn riecht's heut wieder nach allen.": "In der Bahn riecht's heute nach jedem Einzelnen.",
        "Schwitzen im Stehen. Ein Traum.": "Schwitzen ohne Bewegung. Herrlich.",
        "Und im Winter wieder jammern, dass es zu kalt ist.": "Im Januar wünschen sich das alle zurück. Wetten?",
        "Alle starren wieder aufs Regenradar. Als ob das was hilft.": "Das Regenradar hat heute mehr Zuschauer als jede Serie.",
        "Nass ist's. War ja klar.": "Nass. Wer hätte das gedacht.",
        "Regen. Wieder. Natürlich.": "Regen. Mal wieder. Was sonst.",
        "Hauptsache, die Schnecken haben was davon.": "Die Schnecken freuen sich. Immerhin wer.",
        "Im Regen rennen alle, als wär's ein Stück weiter trockener.": "Alle rennen im Regen, als wär's vorne trockener.",
        "Mein Mitleid hält sich in Grenzen. Ich bleib im Trockenen.": "Ich bleib trocken. Mehr Mitgefühl ist heute nicht drin.",
        "Und dann wundern sich alle, warum hier alles so grün ist.": "Darum ist hier alles so grün. Nur so als Erklärung.",
        "„Es gibt kein schlechtes Wetter.“ Doch, gibt's.": "Kein schlechtes Wetter, nur falsche Kleidung? Schön wär's.",
        "Der Hausmeister hat wieder seinen großen Tag.": "Heute ist der Hausmeister der wichtigste Mensch im Haus.",
        "Drei Flocken, und schon heißt's wieder Schneechaos.": "Fünf Zentimeter, und im Radio heißt's Schneechaos.",
        "Der Schneepflug kommt wieder erst, wenn alles getaut ist.": "Bis der Räumdienst kommt, ist alles wieder geschmolzen.",
        "Freuen tun sich nur die Kinder. Die müssen ja nicht schippen.": "Die Kinder jubeln. Schippen müssen ja die anderen.",
        "Gleich fährt keine Bahn mehr, wetten?": "Die Bahn hat bestimmt schon aufgegeben.",
        "Jetzt hamstern's wieder alle Streusalz, als käm die Eiszeit.": "Im Baumarkt ist das Streusalz bestimmt schon weg.",
        "Schneeketten hat natürlich wieder keiner dabei.": "Winterreifen kommen bei manchen ja erst im März drauf.",
        "Erst zu warm, dann zu kalt. Hauptsache, man hat was zum Meckern.": "Zu warm, zu kalt, zu warm. Zum Meckern reicht's immer.",
        "Ausziehen, anziehen. Wie beim Arzt, bloß ohne Krankschreibung.": "Jacke an, Jacke aus. Fast schon Frühsport.",
        "Das Wetter macht heut, was es will. Wie alle anderen auch.": "Heute macht das Wetter, was es will. Wie jeder.",
        "So ein Hin und Her hält ja kein Mensch aus. Ich schon gar nicht.": "Dieses Hin und Her macht mich ganz kirre.",
        "Zwiebelprinzip nennen die das. Ich nenn's Theater.": "Die sagen Zwiebelprinzip. Ich sag Zirkus.",
        "Die Leute gehen aus, als hätten's morgen frei.": "Draußen tun alle, als wär morgen Sonntag.",
        "Falls du noch weggehst: Ich bleib hier. Wie immer.": "Wenn du noch los willst: Ich halt hier die Stellung.",
        "Jetzt werfen sich wieder alle in Schale. Für wen eigentlich?": "Alle machen sich schick. Wer soll das alles anschauen?",
        "Im Bett ist's eh am schönsten. Das Wetter kann mich mal.": "Im Bett ist es sowieso am schönsten. Wetter hin oder her.",
        "Nachts kann ich wenigstens ungestört grantig sein.": "Nachts stört mich wenigstens keiner beim Grummeln.",
        "So spät mach ich nur noch das Nötigste. Wie immer eigentlich.": "Um die Uhrzeit gibt's von mir nur noch das Nötigste.",
        "Spät ist's. Ich zeig das hier trotzdem weiter.": "Schon spät. Ich zeig trotzdem weiter, was ich zeig.",
        "Und wieder hält jemand nachts Wäschewaschen für eine gute Idee.": "Irgendwo im Haus läuft jetzt garantiert der Trockner.",
        "Jetzt passt's Wetter einmal, und du findest sicher trotzdem was.": "Endlich passt das Wetter. Dir fällt bestimmt trotzdem was ein.",
        "Bestes Wetter, und du schaust trotzdem drein wie Montag.": "Traumwetter, und du guckst wie an einem Montag.",
        "Draußen wärst heut sogar du erträglich.": "Bei dem Wetter wärst sogar du gut auszuhalten.",
        "Geh raus, sonst wirst du so grau wie ich.": "Geh an die Luft, bevor du so grau wirst wie ich.",
        "So ein Wetter hätten sich andere mehr verdient.": "Dieses Wetter hast du dir eigentlich nicht verdient.",
        "Durchschnittswetter. Du kennst dich ja aus mit Durchschnitt.": "Mittelmäßiges Wetter. Da fühlst du dich doch zuhause.",
        "Heut bist du mal passend angezogen. Am Rest arbeiten wir noch.": "Die Kleidung passt heute. Der Rest ist noch Baustelle.",
        "Ideales Fensterputzwetter. Deine hätten's nötig.": "Perfekt zum Fensterputzen. Nur so ein Hinweis.",
        "Nichts los da draußen. Wie bei dir am Wochenende.": "Draußen passiert nichts. Kennst du ja von deinen Samstagen.",
        "Bitte nicht wieder die Ärmel um den Bauch knoten.": "Und dann wieder die Jacke um die Hüfte binden? Bitte nicht.",
        "Nachher schwitzt du, als hättest du was geleistet.": "Später schwitzt du, ganz ohne was getan zu haben.",
        "Als ob dein Schrank sowas hergibt.": "Als hättest du was Passendes im Schrank.",
        "Nachher zitterst du wieder wie ein Chihuahua.": "Nachher bibberst du wieder wie ein Chihuahua.",
        "Dick eingepackt gefällst du mir am besten. Man sieht weniger.": "Gut eingemummelt siehst du am besten aus. Weniger sichtbar.",
        "Kalte Füße kriegst du heut nicht nur vor Entscheidungen.": "Heute kriegst du kalte Füße auch ganz ohne Entscheidung.",
        "Bis du heut alles anhast, ist eh schon Frühling.": "Bis du fertig angezogen bist, blühen schon die Krokusse.",
        "Deine Hände sind heut fast so kalt wie dein Herz.": "Heute sind deine Finger so kalt wie deine Kommentare.",
        "Du hängst gleich wieder am Heizkörper wie eine Katze.": "Gleich klebst du wieder an der Heizung wie die Katze.",
        "Gleich träumst du wieder vom Süden. Dann fahr halt endlich hin.": "Du redest wieder von Spanien. Dann buch halt endlich.",
        "Ohne Mütze rausgehen und dann jammern. Kennen wir schon.": "Ohne Mütze raus, dann beschweren. Das kennen wir doch.",
        "Und du wieder in der dünnen Jacke. Na dann viel Spaß.": "Die dünne Jacke wieder? Na, dann viel Vergnügen.",
        "Du wirst heut wieder alle fragen, ob ihnen auch so heiß ist.": "Gleich fragst du wieder jeden, ob dem auch so warm ist.",
        "Heut ist der Schatten dein bester Freund. Dein einziger.": "Dein bester Freund heute: der Schatten. Dein einziger.",
        "Jeder Weg ist dir heut zu weit. Also wie immer.": "Heute ist dir jeder Meter zu viel. Also ein normaler Tag.",
        "Du bist nicht aus Zucker, sagt man. Ich wär mir nicht so sicher.": "Nicht aus Zucker, sagen sie. Bei dir bin ich unsicher.",
        "Du wirst nass. Und dann bin wieder ich schuld.": "Wenn du nass wirst, war's wieder meine Schuld. Klar.",
        "Endlich passt das Wetter mal zu deinem Gesicht.": "Das Wetter passt heute endlich zu deiner Laune.",
        "Lass mich raten: Heut ziehst du die Wildlederschuhe an.": "Ich wette, heute sind die Wildlederschuhe dran.",
        "Tropf mir nachher bloß nicht wieder alles voll.": "Nachher bitte nicht wieder den Flur volltropfen.",
        "Um deine Frisur ist's eh nicht schade.": "Um die Frisur ist es sowieso nicht schade.",
        "Unterm Vordach auf ein Wunder warten, das kannst du.": "Unterm Vordach warten, bis es aufhört. Deine Paradedisziplin.",
        "Wer ohne Schirm geht, braucht nachher nicht jammern.": "Ohne Schirm los und dann jammern. Typisch.",
        "Wie viele Schirme hast du heuer eigentlich schon verloren?": "Wie viele Schirme hast du dieses Jahr schon liegen lassen?",
        "Neben dir wirkt jeder Schneemann lebendig.": "Jeder Schneemann hat heute mehr Ausstrahlung als du.",
        "Du und Glatteis. Das wird wieder was.": "Du auf Glatteis. Ich hol schon mal Popcorn.",
        "Gleich schickst du jedem ein Schneefoto. Die haben auch Fenster.": "Gleich kriegen alle dein Schneefoto. Als hätten die keins.",
        "Schneeballschlacht? Du triffst eh nix.": "Schneeballschlacht? Du triffst doch sowieso nichts.",
        "Schneeschippen wär heut mal Sport für dich. Ausnahmsweise.": "Schnee schippen zählt heute als dein Sportprogramm.",
        "An, aus, wieder an. Wie deine Beziehungen.": "An, aus, an. Kennst du ja aus der Liebe.",
        "Du bist heut garantiert immer eine Schicht daneben.": "Du liegst heute garantiert immer eine Lage daneben.",
        "Heut muss man mitdenken. Schlecht für dich.": "Heute muss man mitdenken. Pech für dich.",
        "Heute trägst du die Jacke mehr spazieren als am Leib.": "Die Jacke wird heute mehr getragen als angezogen.",
        "Morgens frierst du, mittags schwitzt du, abends meckerst du. Ich kenn dich.": "Erst frieren, dann schwitzen, dann meckern. Dein Tag.",
        "Wennst heut alles richtig machst, schreib ich's mir auf.": "Wenn du heute alles richtig anziehst, schreib ich's auf.",
        "Dein Handy kriegt heut wieder mehr Blicke als ich.": "Das Handy kriegt heute wieder mehr Aufmerksamkeit als ich.",
        "Egal, was du heut noch vorhast, ich wär dagegen.": "Was auch immer du heute Abend vorhast: Ich bin dagegen.",
        "Feierabend. Jetzt lass mich auch in Ruhe.": "Abend. Jetzt lass mich auch mal in Ruhe.",
        "Red heut Abend bitte nicht wieder nur übers Wetter.": "Bitte heute Abend mal ein anderes Thema als das Wetter.",
        "Zieh was Schöneres an als das hier.": "Du kannst ruhig was Schöneres anziehen als das.",
        "Und jetzt nicht wieder an den Kühlschrank.": "Finger weg vom Kühlschrank. Ich seh alles.",
        "Nachts wirst du immer so philosophisch. Lass es.": "Um die Uhrzeit wirst du immer tiefsinnig. Bitte nicht.",
        "Noch eine Folge, sagst du. Seit drei Folgen.": "„Nur noch eine Folge.“ Das war vor zwei Folgen.",
        "Schlaf gut. Und bitte leiser als gestern.": "Gute Nacht. Und schnarch bitte nicht wieder so.",
        "Schon wieder so spät? Ab ins Bett.": "So spät noch wach? Ab ins Bett mit dir.",
        "Um die Uhrzeit noch aufs Wetter schauen. Respekt.": "Um die Zeit noch den Wetterbericht checken. Hut ab.",
    },
}

# What each fact situation is, and the drawing it shows with.
SITUATION = {
    "steady": ("sweater_dry", "A steady day, nothing changes."),
    "steady_evening": ("jacket_dry", "A steady evening."),
    "steady_hot": ("heat_dry", "Steady heat all day."),
    "steady_cold": ("coat_dry", "Steady cold all day."),
    "w_scarf": ("bundled_dry", "Bitter cold now; hat, scarf and gloves come off later."),
    "w_coat": ("coat_dry", "Winter coat now; it comes off later."),
    "w_jacket": ("jacket_dry", "Jacket now; it comes off later."),
    "w_hoodie": ("sweater_dry", "Sweater now; it comes off later."),
    "w_water": ("tee_shorts_dry", "It gets hot later."),
    "c_scarf": ("coat_dry", "It gets bitterly cold later."),
    "c_coat": ("jacket_dry", "Winter-coat cold later."),
    "c_jacket": ("sweater_dry", "Jacket weather later."),
    "c_hoodie": ("tee_pants_dry", "Sweater weather later."),
    "c_relief": ("heat_dry", "The heat eases later but stays warm."),
    "arc_warmer": ("jacket_dry", "Warms up and stays warm."),
    "arc_level": ("jacket_dry", "Warms up, then back to how it started."),
    "arc_colder": ("jacket_dry", "Warms up, then colder than now."),
    "shorts_early": ("tee_shorts_dry", "Cool now, shorts weather later."),
    "p_wetter": ("jacket_rain", "A shower later."),
    "p_wetter_long": ("jacket_rain", "Rain later, and it stays."),
    "p_wetter_maybe": ("jacket_rain", "Rain possible later."),
    "p_stays_wet": ("jacket_rain", "Rain all day."),
    "p_drier": ("jacket_rain", "Raining now, stops later."),
    "p_wet_again": ("jacket_rain", "Raining now, a break, then more."),
    "p_snow_coming": ("coat_snow", "Snow later."),
    "p_stays_wet_snow": ("coat_snow", "Snowing all day."),
    "p_drier_snow": ("coat_snow", "Snowing now, stops later."),
    "p_wet_again_snow": ("coat_snow", "Snowing now, a break, then more."),
}


def sentence_case(text):
    return " ".join(p[:1].upper() + p[1:] for p in re.split(r"(?<=[.!?]) ", text))


def render(lang, key, template):
    lang_doc = json.loads((REPO / "lang" / f"{lang}.json").read_text(encoding="utf-8"))
    facts = json.loads((REPO / "prototypes" / "fact-flavour" / "lang" / f"{lang}.json").read_text(encoding="utf-8"))["facts"]
    b = lang_doc["buckets"]
    when = b[3] if key.startswith("c_") else b[1]
    out = (template.replace("{GV}", (facts.get("garments_verb") or [""] * 4)[2])
           .replace("{GP}", facts["garments_pron"][2]).replace("{G}", facts["garments"][2])
           .replace("{WHEN2}", b[4]).replace("{WHEN}", when).replace("{WHENP}", b[2]))
    return sentence_case(out)


def main():
    lines = []
    for lang, keys in FACTS.items():
        current = json.loads((REPO / "prototypes" / "fact-flavour" / "lang" / f"{lang}.json").read_text(encoding="utf-8"))["facts"]
        for key, variants in keys.items():
            sprite, meaning = SITUATION[key]
            first = current[key][0] if isinstance(current[key], list) else current[key]
            meaning += f" Current wording: \u201c{render(lang, key, first)}\u201d"
            for t in variants:
                lines.append({"lang": lang, "path": f"fact_0.{key}", "text": render(lang, key, t),
                              "template": t, "batch": "F" + lang[0].upper(), "sprite": sprite,
                              "meaning": f"Fact line variant. {meaning}"})
    for lang, pairs in FLAVOUR.items():
        doc = json.loads((REPO / "prototypes" / "fact-flavour" / "lang" / f"{lang}.json").read_text(encoding="utf-8"))
        where = {t: (lv[-2:], m) for lv in ("flavour_10", "flavour_11") for m, v in doc[lv].items() for t in v}
        for original, variant in pairs.items():
            if original not in where:
                raise SystemExit(f"not in the pool: {original!r}")
            level, mood = where[original]
            lines.append({"lang": lang, "path": f"flavour_{level}.{mood}", "text": variant,
                          "variant_of": original, "batch": "V" + lang[0].upper(),
                          "meaning": f"Reworded. The kept line it varies: \u201c{original}\u201d"})
    over = [l["text"] for l in lines if l["path"].startswith("flavour") and len(l["text"]) > 65]
    (HERE / f"{ROUND}.json").write_text(json.dumps({"round": ROUND, "lines": lines}, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"{ROUND}: {len(lines)} lines ({sum(l['path'].startswith('fact') for l in lines)} fact, "
          f"{sum(l['path'].startswith('flavour') for l in lines)} flavour); over 65 chars: {over}")


if __name__ == "__main__":
    main()
