#!/usr/bin/env python3
"""
Generates src/shared.transitional.liquid from src/shared.liquid + lang/*.json.

The transitional markup is what you paste into TRMNL in step 1 of the
rollout (see docs/MIGRATION.md). It behaves like this:

  no second polling URL yet -> weather at the root, texts from the
                               embedded copies below. Renders exactly
                               like the version before this refactor.
  second polling URL present -> weather from IDX_0, texts from IDX_1.
                                The embedded copies go unused.

So it is correct whichever order the markup update and the polling URL
update reach a given device, which is the whole point: a recipe update
pushes markup to every installed user immediately, but there is no
guarantee the polling config lands at the same moment.

Once every device is on the transitional markup AND the second polling
URL is live, paste src/shared.liquid to drop the embedded copies.

Regenerate after any edit to src/shared.liquid or the language files:
    python3 tools/build_transitional.py
"""

import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
FINAL = REPO / "src" / "shared.liquid"
OUT = REPO / "src" / "shared.transitional.liquid"

LEVELS = ["0", "10", "11"]
LANGS = ["en", "de"]


def liquid_escape(text):
    """The libraries are stored in a capture block, so the only thing that
    could break them is a Liquid tag opener. None of the phrasing contains
    one, but fail loudly rather than emit a broken template."""
    for bad in ("{{", "{%", "||", ";;"):
        if bad in text:
            raise ValueError(f"line cannot be embedded, contains {bad!r}: {text[:60]!r}")
    return text


def build_capture(name, library):
    entries = []
    for key, lines in library.items():
        for line in lines:
            liquid_escape(line)
        entries.append(f"{key}::" + "||".join(lines))
    body = "\n;;".join(entries)
    return f"{{%- capture {name} -%}}\n{body}\n{{%- endcapture -%}}\n"


def csv(values):
    for v in values:
        if "," in v:
            raise ValueError(f"cannot embed value containing a comma: {v!r}")
    return ",".join(values)


def replace_once(text, old, new, label):
    if text.count(old) != 1:
        raise SystemExit(
            f"anchor {label!r} matched {text.count(old)} times, expected exactly 1.\n"
            "src/shared.liquid changed shape; update tools/build_transitional.py."
        )
    return text.replace(old, new)


COMMENT = re.compile(r"\{%-?\s*comment\s*-?%\}.*?\{%-?\s*endcomment\s*-?%\}\n?", re.DOTALL)

HEADER = """{%- comment %}
WHAT TO WEAR, v3 - shared markup, TRANSITIONAL BUILD.

Generated by tools/build_transitional.py - do not hand edit.
Source of truth is src/shared.liquid plus lang/<code>.json.

Comments are stripped and the text libraries are inlined so this fits
under the 100 KB markup ceiling. Paste this in rollout step 1, then
src/shared.liquid in step 3. See docs/MIGRATION.md.
{%- endcomment %}
"""


def main():
    src = FINAL.read_text(encoding="utf-8")

    # Comments are for people reading the repo. This build has a byte budget,
    # and the reader of this particular file is the TRMNL markup editor.
    src = COMMENT.sub("", src)
    src = re.sub(r"\n{3,}", "\n\n", src).lstrip("\n")

    # Deliberately the FROZEN pre-rewrite snapshot, not the live language
    # files. These inlined copies only serve devices that have the new markup
    # but not yet the texts polling URL; for them, "what they saw yesterday"
    # is the correct output. Devices past that point read lang/<code>.json.
    # It is also what keeps this build under the 100 KB ceiling: the rewritten
    # corpus is larger and would not fit. See lang/.rollout-fallback/README.md.
    fallback = REPO / "lang" / ".rollout-fallback"
    langs = {
        code: json.loads((fallback / f"{code}.json").read_text(encoding="utf-8"))
        for code in LANGS
    }

    # ---- 1. embedded copies of the libraries, keyed exactly as before ----
    captures = ["\n{%- comment %} embedded libraries, transitional only {%- endcomment %}\n"]
    for code in LANGS:
        doc = langs[code]
        for level in LEVELS:
            captures.append(build_capture(f"temp_{level}_{code}", doc[f"temp_{level}"]))
            captures.append(build_capture(f"precip_{level}_{code}", doc[f"precip_{level}"]))
    captures_blob = "\n".join(captures)

    # ---- 2. garments, buckets and relative need inline fallbacks ----
    garment_new = []
    for code in LANGS:
        doc = langs[code]
        garment_new.append(
            f"    {{%- elsif lang == '{code}' -%}}\n"
            f"      {{%- assign GARMENTS_N = '{csv(doc['garments']['n'])}' | split: ',' -%}}\n"
            f"      {{%- assign GARMENTS_A = '{csv(doc['garments']['a'])}' | split: ',' -%}}\n"
        )
    en = langs["en"]
    garment_block = (
        "    {%- if texts_ok -%}\n"
        "      {%- assign GARMENTS_N = texts.garments.n -%}\n"
        "      {%- assign GARMENTS_A = texts.garments.a -%}\n"
        + "".join(garment_new)
        + "    {%- else -%}\n"
        f"      {{%- assign GARMENTS_N = '{csv(en['garments']['n'])}' | split: ',' -%}}\n"
        f"      {{%- assign GARMENTS_A = '{csv(en['garments']['a'])}' | split: ',' -%}}\n"
        "    {%- endif -%}"
    )
    src = replace_once(
        src,
        "    {%- assign GARMENTS_N = texts.garments.n -%}\n"
        "    {%- assign GARMENTS_A = texts.garments.a -%}",
        garment_block,
        "garments",
    )

    time_new = []
    for code in LANGS:
        doc = langs[code]
        time_new.append(
            f"    {{%- elsif lang == '{code}' -%}}\n"
            f"      {{%- assign BUCKETS = '{csv(doc['buckets'])}' | split: ',' -%}}\n"
            f"      {{%- assign RELATIVE = '{csv(doc['relative'])}' | split: ',' -%}}\n"
        )
    time_block = (
        "    {%- if texts_ok -%}\n"
        "      {%- assign BUCKETS = texts.buckets -%}\n"
        "      {%- assign RELATIVE = texts.relative -%}\n"
        + "".join(time_new)
        + "    {%- else -%}\n"
        f"      {{%- assign BUCKETS = '{csv(en['buckets'])}' | split: ',' -%}}\n"
        f"      {{%- assign RELATIVE = '{csv(en['relative'])}' | split: ',' -%}}\n"
        "    {%- endif -%}"
    )
    src = replace_once(
        src,
        "    {%- assign BUCKETS = texts.buckets -%}\n"
        "    {%- assign RELATIVE = texts.relative -%}",
        time_block,
        "time wording",
    )

    # ---- 3. drop the texts_ok guards: the embedded copies always resolve ----
    for old, new, label in [
        ("{%- if band_rank <= 5 and texts_ok -%}", "{%- if band_rank <= 5 -%}", "band guard"),
        ("{%- if temp_scenario != '' and texts_ok -%}", "{%- if temp_scenario != '' -%}", "temp token guard"),
        ("{%- if is_arc and texts_ok -%}", "{%- if is_arc -%}", "arc guard"),
        ("{%- if wants_whenp and texts_ok -%}", "{%- if wants_whenp -%}", "whenp guard"),
        (
            "{%- if is_error == false and show_future_suggestions == 'on' and texts_ok -%}",
            "{%- if is_error == false and show_future_suggestions == 'on' -%}",
            "hint guard",
        ),
    ]:
        src = replace_once(src, old, new, label)

    # ---- 4. library lookup falls back to parsing the embedded copies ----
    temp_lookup = (
        "  {%- assign temp_lib_key = 'temp_' | append: sarcasm_level -%}\n"
        "  {%- assign t_arr = nil -%}\n"
        "  {%- if texts_ok -%}\n"
        "    {%- assign temp_lib = texts[temp_lib_key] -%}\n"
        "    {%- assign t_arr = temp_lib[scenario] -%}\n"
        "  {%- else -%}\n"
        "    {%- assign embedded_key = temp_lib_key | append: '_' | append: lang -%}\n"
        "    {%- case embedded_key -%}\n"
        + "".join(
            f"      {{%- when 'temp_{level}_{code}' -%}}{{%- assign temp_lib = temp_{level}_{code} -%}}\n"
            for code in LANGS
            for level in LEVELS
        )
        + "      {%- else -%}{%- assign temp_lib = temp_0_en -%}\n"
        "    {%- endcase -%}\n"
        "    {%- assign t_entries = temp_lib | split: ';;' -%}\n"
        "    {%- for e in t_entries -%}\n"
        "      {%- assign parts = e | strip | split: '::' -%}\n"
        "      {%- if parts[0] == scenario -%}\n"
        "        {%- assign t_arr = parts[1] | split: '||' -%}\n"
        "        {%- break -%}\n"
        "      {%- endif -%}\n"
        "    {%- endfor -%}\n"
        "  {%- endif -%}"
    )
    src = replace_once(
        src,
        "  {%- assign temp_lib_key = 'temp_' | append: sarcasm_level -%}\n"
        "  {%- assign temp_lib = texts[temp_lib_key] -%}\n"
        "  {%- assign t_arr = temp_lib[scenario] -%}",
        temp_lookup,
        "temp lookup",
    )

    precip_lookup = (
        "    {%- assign precip_lib_key = 'precip_' | append: sarcasm_level -%}\n"
        "    {%- assign p_arr = nil -%}\n"
        "    {%- if texts_ok -%}\n"
        "      {%- assign precip_lib = texts[precip_lib_key] -%}\n"
        "      {%- assign p_arr = precip_lib[p_key] -%}\n"
        "    {%- else -%}\n"
        "      {%- assign embedded_key = precip_lib_key | append: '_' | append: lang -%}\n"
        "      {%- case embedded_key -%}\n"
        + "".join(
            f"        {{%- when 'precip_{level}_{code}' -%}}{{%- assign precip_lib = precip_{level}_{code} -%}}\n"
            for code in LANGS
            for level in LEVELS
        )
        + "        {%- else -%}{%- assign precip_lib = precip_0_en -%}\n"
        "      {%- endcase -%}\n"
        "      {%- assign p_entries = precip_lib | split: ';;' -%}\n"
        "      {%- for e in p_entries -%}\n"
        "        {%- assign parts = e | strip | split: '::' -%}\n"
        "        {%- if parts[0] == p_key -%}\n"
        "          {%- assign p_arr = parts[1] | split: '||' -%}\n"
        "          {%- break -%}\n"
        "        {%- endif -%}\n"
        "      {%- endfor -%}\n"
        "    {%- endif -%}"
    )
    src = replace_once(
        src,
        "    {%- assign precip_lib_key = 'precip_' | append: sarcasm_level -%}\n"
        "    {%- assign precip_lib = texts[precip_lib_key] -%}\n"
        "    {%- assign p_arr = precip_lib[p_key] -%}",
        precip_lookup,
        "precip lookup",
    )

    # ---- 5. splice the captures in just before the hint builder ----
    anchor = "{%- assign temp_clause = '' -%}"
    src = replace_once(src, anchor, captures_blob + "\n" + anchor, "hint builder")

    OUT.write_text(HEADER + src, encoding="utf-8")
    size = OUT.stat().st_size
    print(f"wrote {OUT.relative_to(REPO)}  ({size:,} bytes)")
    if size > 100_000:
        print("WARNING: over the 100 KB markup ceiling", file=sys.stderr)
        return 1
    print(f"headroom under 100 KB: {100_000 - size:,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
