#!/usr/bin/env python3
"""
Turns the review page's votes into files the repo keeps.

    python3 tools/review_sync.py <decisions.json> [--fixes]

<decisions.json> is either the page's "Save decisions file" export
({"decisions": [...]}) or a plain list of decision documents, which is
what Claude gets when it reads the page's database directly.

Writes, per language:

    review/decisions/<lang>.json   every vote ever cast, keyed by line id.
                                   The memory: a vetoed line never comes back.
    review/examples/<lang>.md      starred lines, by key and level. The
                                   writer's examples for the next round.
    review/dont/<lang>.md          vetoed lines with their tags and notes.
                                   The writer's "don't" list.

With --fixes it also writes build/review/<lang>_fixes.json for
tools/apply_review.py: vetoed shipped lines are deleted, starred or kept
candidates are appended. Review it with --dry-run before applying.
"""

import collections
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "review"
LEVEL_NAME = {"0": "plain", "10": "dry", "11": "sarcastic"}
FIELDS = ("lang", "level", "key", "path", "text", "source", "batch", "round",
          "verdict", "tags", "note", "updatedAt")


def load_votes(path):
    data = json.loads(pathlib.Path(path).read_text(encoding="utf-8"))
    if isinstance(data, dict):
        data = data.get("decisions", data.get("docs", []))
    votes = []
    for d in data:
        d = d.get("data", d) if isinstance(d, dict) and "data" in d else d
        if d.get("id") and d.get("lang") and d.get("text"):
            votes.append(d)
    return votes


def merge(lang, votes):
    target = OUT / "decisions" / f"{lang}.json"
    known = json.loads(target.read_text(encoding="utf-8")) if target.exists() else {}
    changed = 0
    for v in votes:
        old = known.get(v["id"])
        if old and old.get("updatedAt", "") >= v.get("updatedAt", ""):
            continue
        known[v["id"]] = {k: v.get(k, "") for k in FIELDS if k != "lang"}
        changed += 1
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(dict(sorted(known.items())), ensure_ascii=False, indent=1) + "\n",
                      encoding="utf-8")
    return known, changed


def grouped(known, verdict):
    by = collections.defaultdict(list)
    for d in known.values():
        if d.get("verdict") == verdict:
            by[(d["key"].removesuffix("_j"), d["key"], d["level"])].append(d)
    return sorted(by.items())


def write_examples(lang, known):
    lines = [f"# Starred lines ({lang})", "",
             "Generated by `tools/review_sync.py` from the review page. These",
             "are the owner's taste: write the next round to sit beside them.",
             "Do not edit by hand; vote on the page instead.", ""]
    for (_, key, level), items in grouped(known, "star"):
        lines.append(f"## {key} · {LEVEL_NAME.get(level, level)}")
        lines.append("")
        for d in sorted(items, key=lambda d: d["text"]):
            lines.append(f"- {d['text']}" + (f"  \n  _{d['note']}_" if d.get("note") else ""))
        lines.append("")
    path = OUT / "examples" / f"{lang}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_dont(lang, known):
    vetoed = [d for d in known.values() if d.get("verdict") == "veto"]
    tags = collections.Counter(t for d in vetoed for t in d.get("tags") or [])
    lines = [f"# Vetoed lines ({lang})", "",
             "Generated by `tools/review_sync.py`. Never reuse these lines or",
             "their skeletons. Tags say why.", ""]
    if tags:
        lines.append("Most common reasons: " + ", ".join(f"{t} ({n})" for t, n in tags.most_common()) + ".")
        lines.append("")
    for (_, key, level), items in grouped(known, "veto"):
        lines.append(f"## {key} · {LEVEL_NAME.get(level, level)}")
        lines.append("")
        for d in sorted(items, key=lambda d: d["text"]):
            why = ", ".join(d.get("tags") or []) or "no tag"
            lines.append(f"- {d['text']}  \n  _{why}" + (f": {d['note']}" if d.get("note") else "") + "_")
        lines.append("")
    path = OUT / "dont" / f"{lang}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_fixes(lang, known):
    doc = json.loads((REPO / "lang" / f"{lang}.json").read_text(encoding="utf-8"))
    out = []
    for d in known.values():
        m = re.match(r"^((?:temp|precip)_\d+)\.([a-z_]+)", d["path"])
        if not m:
            continue
        section, key = m.groups()
        current = (doc.get(section) or {}).get(key) or []
        if d.get("source") == "candidate":
            if d.get("verdict") in ("star", "keep") and d["text"] not in current:
                out.append({"path": f"{section}.{key}[{len(current)}]", "old": "", "new": d["text"],
                            "why": f"{d['verdict']} in review" + (f" ({d['round']})" if d.get("round") else "")})
        elif d.get("verdict") == "veto" and d["text"] in current:
            # Locate by text, not by the stored index: the file may have
            # moved since the vote.
            i = current.index(d["text"])
            out.append({"path": f"{section}.{key}[{i}]", "old": d["text"], "new": None,
                        "why": "vetoed: " + (", ".join(d.get("tags") or []) or "no tag")})
    target = REPO / "build" / "review" / f"{lang}_fixes.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps({"summary": "From the review page.", "replacements": out},
                                 ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return target, len(out)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        print(__doc__.strip())
        return 2
    votes = load_votes(args[0])
    by_lang = collections.defaultdict(list)
    for v in votes:
        by_lang[v["lang"]].append(v)
    for lang, vs in sorted(by_lang.items()):
        known, changed = merge(lang, vs)
        write_examples(lang, known)
        write_dont(lang, known)
        counts = collections.Counter(d.get("verdict") or "tag/note only" for d in known.values())
        print(f"{lang}: {changed} new or changed, now " + ", ".join(f"{n} {k}" for k, n in sorted(counts.items())))
        if "--fixes" in sys.argv:
            target, n = write_fixes(lang, known)
            print(f"    {n} fix(es) -> {target.relative_to(REPO)}  (apply: python3 tools/apply_review.py {target.relative_to(REPO)} --dry-run)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
